"""
Exploratory Data Analysis for the retail demand forecasting dataset.

Produces:
  - docs/eda_report.md
  - assets/*.png
  - data/processed/eda_summary.json

Usage:
    python -m src.data.eda --input data/raw/sales.csv
"""

from __future__ import annotations

import argparse
import json
import logging
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import pandas as pd

logging.basicConfig(level=logging.INFO, format="%(asctime)s | %(levelname)-8s | %(message)s")
logger = logging.getLogger(__name__)


def load_data(path: str) -> pd.DataFrame:
    df = pd.read_csv(path, parse_dates=["date"])
    logger.info("Loaded %d rows, %d columns from %s", len(df), df.shape[1], path)
    return df


def profile_dataset(df: pd.DataFrame) -> dict:
    daily_total = df.groupby("date")["units_sold"].sum()
    dow_avg = df.assign(dow=df["date"].dt.day_name()).groupby("dow")["units_sold"].mean()
    dow_order = [
        "Monday",
        "Tuesday",
        "Wednesday",
        "Thursday",
        "Friday",
        "Saturday",
        "Sunday",
    ]
    dow_avg = dow_avg.reindex(dow_order)

    promo_lift_pct = (
        df[df["is_promo"] == 1]["units_sold"].mean() / df[df["is_promo"] == 0]["units_sold"].mean()
        - 1
    ) * 100
    holiday_lift_pct = (
        df[df["is_holiday"] == 1]["units_sold"].mean()
        / df[df["is_holiday"] == 0]["units_sold"].mean()
        - 1
    ) * 100

    summary = {
        "n_rows": int(len(df)),
        "n_days": int(df["date"].nunique()),
        "n_stores": int(df["store_id"].nunique()),
        "n_items": int(df["item_id"].nunique()),
        "n_missing_values": int(df.isna().sum().sum()),
        "date_range": [str(df["date"].min().date()), str(df["date"].max().date())],
        "total_units_sold": int(df["units_sold"].sum()),
        "avg_daily_total_units": round(float(daily_total.mean()), 1),
        "weekend_vs_weekday_avg": {
            "weekday_avg": round(
                float(dow_avg[["Monday", "Tuesday", "Wednesday", "Thursday"]].mean()), 1
            ),
            "weekend_avg": round(float(dow_avg[["Friday", "Saturday", "Sunday"]].mean()), 1),
        },
        "promo_lift_pct": round(float(promo_lift_pct), 1),
        "holiday_lift_pct": round(float(holiday_lift_pct), 1),
        "sales_by_category": {
            k: round(float(v), 1)
            for k, v in df.groupby("item_category")["units_sold"]
            .mean()
            .sort_values(ascending=False)
            .items()
        },
        "pct_promo_days": round(float(df["is_promo"].mean() * 100), 2),
    }
    return summary


def plot_daily_total_timeseries(df: pd.DataFrame, out_path: Path) -> None:
    daily_total = df.groupby("date")["units_sold"].sum()
    fig, ax = plt.subplots(figsize=(9, 4.5))
    ax.plot(daily_total.index, daily_total.values, color="#2980b9", linewidth=1)
    ax.set_xlabel("Date")
    ax.set_ylabel("Total units sold (all stores/items)")
    ax.set_title("Daily Total Demand Over Time")
    fig.tight_layout()
    fig.savefig(out_path, dpi=150)
    plt.close(fig)


def plot_day_of_week_pattern(df: pd.DataFrame, out_path: Path) -> None:
    dow_order = [
        "Monday",
        "Tuesday",
        "Wednesday",
        "Thursday",
        "Friday",
        "Saturday",
        "Sunday",
    ]
    dow_avg = (
        df.assign(dow=df["date"].dt.day_name())
        .groupby("dow")["units_sold"]
        .mean()
        .reindex(dow_order)
    )
    fig, ax = plt.subplots(figsize=(8, 4.5))
    colors = ["#2980b9"] * 4 + ["#c0392b"] * 3
    ax.bar(dow_avg.index, dow_avg.values, color=colors)
    ax.set_ylabel("Avg units sold per row")
    ax.set_title("Average Demand by Day of Week")
    plt.xticks(rotation=30, ha="right")
    fig.tight_layout()
    fig.savefig(out_path, dpi=150)
    plt.close(fig)


def plot_category_comparison(df: pd.DataFrame, out_path: Path) -> None:
    cat_avg = df.groupby("item_category")["units_sold"].mean().sort_values()
    fig, ax = plt.subplots(figsize=(8, 4.5))
    ax.barh(cat_avg.index, cat_avg.values, color="#27ae60")
    ax.set_xlabel("Avg units sold per row")
    ax.set_title("Average Demand by Item Category")
    fig.tight_layout()
    fig.savefig(out_path, dpi=150)
    plt.close(fig)


def write_markdown_report(summary: dict, out_path: Path) -> None:
    lines = [
        "# Exploratory Data Analysis Report",
        "",
        "> Auto-generated by `src/data/eda.py`. Dataset is synthetic (see data provenance note "
        "in `src/data/generate_data.py`) but modeled on realistic retail seasonality patterns.",
        "",
        "## Dataset Overview",
        f"- Rows: **{summary['n_rows']:,}** ({summary['n_days']} days x {summary['n_stores']} stores x "
        f"{summary['n_items']} items)",
        f"- Date range: **{summary['date_range'][0]}** to **{summary['date_range'][1]}**",
        f"- Missing values: **{summary['n_missing_values']}**",
        f"- Total units sold: **{summary['total_units_sold']:,}**",
        f"- Average daily total demand: **{summary['avg_daily_total_units']:,}** units/day",
        "",
        "## Key Findings",
        f"1. **Weekend effect is real**: weekday avg {summary['weekend_vs_weekday_avg']['weekday_avg']} "
        f"units/row vs weekend avg {summary['weekend_vs_weekday_avg']['weekend_avg']} units/row.",
        f"2. **Promotions lift sales by {summary['promo_lift_pct']}%** on average "
        f"({summary['pct_promo_days']}% of rows are promo days) — this must be a model feature, "
        "not left as unexplained variance.",
        f"3. **Holidays shift demand by {summary['holiday_lift_pct']}%** on average (mix of spikes like "
        "Christmas Eve and drops like Christmas Day itself).",
        "4. **Category matters** — see `sales_by_category` below; produce and beverages have the "
        "highest average unit volume.",
        "",
        "## Average Demand by Category",
        "| Category | Avg units/row |",
        "|---|---|",
    ]
    for cat, val in summary["sales_by_category"].items():
        lines.append(f"| {cat} | {val} |")

    lines += [
        "",
        "## Charts",
        "![Daily total demand](../assets/daily_total_timeseries.png)",
        "![Day of week pattern](../assets/day_of_week_pattern.png)",
        "![Category comparison](../assets/category_comparison.png)",
        "",
        "## Data Quality Checks",
        f"- No missing values: {'PASS' if summary['n_missing_values'] == 0 else 'FAIL'}",
        "",
    ]
    out_path.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description="Run EDA on the retail sales dataset")
    parser.add_argument("--input", type=str, default="data/raw/sales.csv")
    parser.add_argument("--assets-dir", type=str, default="assets")
    parser.add_argument("--docs-dir", type=str, default="docs")
    parser.add_argument("--processed-dir", type=str, default="data/processed")
    args = parser.parse_args()

    df = load_data(args.input)
    summary = profile_dataset(df)

    assets_dir = Path(args.assets_dir)
    docs_dir = Path(args.docs_dir)
    processed_dir = Path(args.processed_dir)
    for d in (assets_dir, docs_dir, processed_dir):
        d.mkdir(parents=True, exist_ok=True)

    plot_daily_total_timeseries(df, assets_dir / "daily_total_timeseries.png")
    plot_day_of_week_pattern(df, assets_dir / "day_of_week_pattern.png")
    plot_category_comparison(df, assets_dir / "category_comparison.png")

    write_markdown_report(summary, docs_dir / "eda_report.md")
    with open(processed_dir / "eda_summary.json", "w", encoding="utf-8") as f:
        json.dump(summary, f, indent=2)

    logger.info("EDA complete. Report: %s", docs_dir / "eda_report.md")
    logger.info("Summary: %s", json.dumps(summary, indent=2)[:600])


if __name__ == "__main__":
    main()
